### ISSUE TITLE
hide your firebase app config dude

### ISSUE THREAD

**Issue by azeek21** [zoir-dev/market#1]
Use .env files on your deploys and share .env.exaple files in public so others can use your app but don't share them directly.
Learn more -> https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by zoir-dev** [comment]
Assalamu alaikum!
🤔😳 Thank u bro it is my bad I didn't think about it

**Comment by azeek21** [comment]
Welcome.

**Comment by azeek21** [comment]
Welcome
